import {
    PiHouseLineDuotone,
    PiArrowsInDuotone,
    PiBookOpenUserDuotone,
    PiBookBookmarkDuotone,
    PiAcornDuotone,
    PiBagSimpleDuotone,
    PiUsersDuotone,
    PiUserDuotone,
    PiBuildingsDuotone,
    PiCubeDuotone,
    PiListChecksDuotone,
    PiShieldCheckDuotone,
    PiGearDuotone,
    PiGridFourDuotone,
    PiWalletDuotone,
    PiCalendarDuotone,
    PiClockDuotone,
    PiChartBarDuotone,
    PiFileTextDuotone,
    PiLockDuotone,
    PiTreeStructureDuotone,
    PiTagDuotone,
    PiMapPinDuotone,
    PiBriefcaseDuotone,
    PiIdentificationBadgeDuotone,
    PiHandshakeDuotone,
    PiAddressBookDuotone,
    PiUsersThreeDuotone,
    PiChartLineDuotone,
    PiStorefrontDuotone,
} from 'react-icons/pi'
import type { JSX } from 'react'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    // Original template icons
    home: <PiHouseLineDuotone />,
    singleMenu: <PiAcornDuotone />,
    collapseMenu: <PiArrowsInDuotone />,
    groupSingleMenu: <PiBookOpenUserDuotone />,
    groupCollapseMenu: <PiBookBookmarkDuotone />,
    groupMenu: <PiBagSimpleDuotone />,

    // Project-specific icons (matched to backend icon field values)
    dashboard: <PiHouseLineDuotone />,
    'layout-dashboard': <PiHouseLineDuotone />,
    users: <PiUsersDuotone />,
    pengguna: <PiUsersDuotone />,
    user: <PiUserDuotone />,
    perusahaan: <PiBuildingsDuotone />,
    buildings: <PiBuildingsDuotone />,
    modul: <PiCubeDuotone />,
    cube: <PiCubeDuotone />,
    paket: <PiTagDuotone />,
    menu: <PiListChecksDuotone />,
    peran: <PiShieldCheckDuotone />,
    shield: <PiShieldCheckDuotone />,
    'izin-peran': <PiLockDuotone />,
    izinPeran: <PiLockDuotone />,
    lock: <PiLockDuotone />,
    aksesModul: <PiGridFourDuotone />,
    'akses-modul': <PiGridFourDuotone />,
    menuModul: <PiTreeStructureDuotone />,
    'menu-modul': <PiTreeStructureDuotone />,
    settings: <PiGearDuotone />,
    gear: <PiGearDuotone />,
    wallet: <PiWalletDuotone />,
    payroll: <PiWalletDuotone />,
    calendar: <PiCalendarDuotone />,
    attendance: <PiClockDuotone />,
    clock: <PiClockDuotone />,
    report: <PiFileTextDuotone />,
    'file-text': <PiFileTextDuotone />,
    laporan: <PiFileTextDuotone />,
    chart: <PiChartBarDuotone />,
    'chart-bar': <PiChartBarDuotone />,
    employee: <PiIdentificationBadgeDuotone />,
    karyawan: <PiIdentificationBadgeDuotone />,
    location: <PiMapPinDuotone />,
    briefcase: <PiBriefcaseDuotone />,
    crm: <PiHandshakeDuotone />,
    organisasi: <PiUsersThreeDuotone />,
    departemen: <PiBuildingsDuotone />,
    jabatan: <PiBriefcaseDuotone />,
    'lokasi-kantor': <PiMapPinDuotone />,
    'struktur-organisasi': <PiTreeStructureDuotone />,
    handshake: <PiHandshakeDuotone />,
    'address-book': <PiAddressBookDuotone />,
    addressBook: <PiAddressBookDuotone />,
    'users-three': <PiUsersThreeDuotone />,
    usersThree: <PiUsersThreeDuotone />,
    'chart-line': <PiChartLineDuotone />,
    chartLine: <PiChartLineDuotone />,
    storefront: <PiStorefrontDuotone />,
}

export default navigationIcon
